### ISSUE TITLE
"Can't play this video."

### ISSUE THREAD

**Issue by medavox** [theScrabi/NewPipe#117]
Just discovered this while using the app in bed, thought I'd report it before i forgot.

Search for "cupcake lander", tap the video named "Just the two of us...", and attempt to play it by tapping the red play button over the video thumbnail. Instead of the video playing, you should see the message in the issue title popup as a dialog box.

I might check this out myself tomorrow, unless someone beats me to it :)

**Comment by theScrabi** [comment]
I noticed that NP does strange things on some devices :/ because I don't have that error.

**Comment by medavox** [comment]
Hmm, I investigated this further, and it looks like YouTube may have changed the API on the version of the page I am receiving... It may be a different version for you.

I get these errors:

```
W/System.err: java.lang.Exception: failed to find pattern "(var gr=function\([a-zA-Z0-9_]*\)\{.+?\})"
W/System.err:     at org.schabi.newpipe.services.youtube.YoutubeVideoExtractor.matchGroup1(YoutubeVideoExtractor.java:611)
W/System.err:     at org.schabi.newpipe.services.youtube.YoutubeVideoExtractor.loadDecryptionCode(YoutubeVideoExtractor.java:564)
W/System.err:     at org.schabi.newpipe.services.youtube.YoutubeVideoExtractor.<init>(YoutubeVideoExtractor.java:95)
W/System.err:     at org.schabi.newpipe.services.youtube.YoutubeService.getExtractorInstance(YoutubeService.java:38)
W/System.err:     at org.schabi.newpipe.VideoItemDetailFragment$VideoExtractorRunnable.run(VideoItemDetailFragment.java:111)
W/System.err:     at java.lang.Thread.run(Thread.java:841)
W/class org.schabi.newpipe.services.youtube.YoutubeVideoExtractor: failed to find pattern ";([A-Za-z0-9_\$]{2})\...\(" inside of ";"
W/System.err: java.lang.Exception: failed to find pattern ";([A-Za-z0-9_\$]{2})\...\("
W/System.err:     at org.schabi.newpipe.services.youtube.YoutubeVideoExtractor.matchGroup1(YoutubeVideoExtractor.java:611)
W/System.err:     at org.schabi.newpipe.services.youtube.YoutubeVideoExtractor.loadDecryptionCode(YoutubeVideoExtractor.java:567)
W/System.err:     at org.schabi.newpipe.services.youtube.YoutubeVideoExtractor.<init>(YoutubeVideoExtractor.java:95)
W/System.err:     at org.schabi.newpipe.services.youtube.YoutubeService.getExtractorInstance(YoutubeService.java:38)
W/System.err:     at org.schabi.newpipe.VideoItemDetailFragment$VideoExtractorRunnable.run(VideoItemDetailFragment.java:111)
W/System.err:     at java.lang.Thread.run(Thread.java:841)
W/class org.schabi.newpipe.services.youtube.YoutubeVideoExtractor: failed to find pattern "(var =\{.+?\}\};)" inside of "var _yt_player={};(function(g){var window=this;var h,n=function(a){return void 0!==a},r=function(a,b,c){a=a.split(".");c=c||q;a[0]in c||!c.execScript||c.execScript("var "+a[0]);for(var d;a.length&&(d=a.shift());)!a.length&&n(b)?c[d]=b:c[d]?c=c[d]:c=c[d]={}},v=function(a,b){for(var c=a.split("."),d=b||q,e;e=c.shift();)if(null!=d[e])d=d[e];else return null;return d},w=function(){},aa=function(a){a.getInstance=function(){return a.Mb?a.Mb:a.Mb=new a}},ba=function(a){var b=typeof a;if("object"==b)if(a){if(a instanceof Array)return"array";if(a instanceof Object)return b;var c=Object.prototype.toString.call(a);if("[object Window]"==c)return"object";if("[object Array]"==c||"number"==typeof a.length&&"undefined"!=typeof a.splice&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("splice"))return"array";if("[object Function]"==c||"undefined"!=typeof a.call&&"undefined"!=typeof a.propertyIsEnumerable&&!a.propertyIsEnumerable("call"))return"function"}else return"null";else if("function"==b&&"undefined"==typeof a.call)return"object";return b},ca=function(a){return null===a},da=function(a){return"array"==ba(a)},ea=function(a){var b=ba(a);return"array"==b||"object"==b&&"number"==typeof a.length},z=function(a){return"string"==typeof a},fa=function(a){return"number"==typeof a},ga=function(a){return"function"==ba(a)},ha=function(a){var b=typeof a;return"object"==b&&null!=a||"function"==b},la=function(a){return a[ia]||(a[ia]=++ka)},ma=function(a,b,c){return a.call.apply(a.bind,arguments)},na=function(a,b,c){if(!a)throw Error();if(2<arguments.length){var d=Array.prototype.slice.call(arguments,2);return function(){var c=Array.prototype.slice.call(arguments);Array.prototype.unshift.apply(c,d);return a.apply(b,c)}}return function(){return a.apply(b,arguments)}},A=function(a,b,c){A=Function.prototype.bind&&-1!=Function.prototype.bind.toString().indexOf("native code")?ma:na;return A.apply(null,arguments)},oa=function(a,b){var c=Array.prototype.slice.call(arguments,1);return function(){var b=c.slice();b.push.apply(b,arguments);return a.apply(this,b)}},pa=function(a,b){for(var c in b)a[c]=b[c]},qa=function(a,b){b&&(a=a.replace(/\{\$([^}]+)}/g,function(a,d){return null!=b&&d in b?b[d]:a}));return a},B=function(a,b){function c(){}c.prototype=b.prototype;a.M=b.prototype;a.prototype=new c;a.prototype.constructor=a;a.base=function(a,c,f){for(var k=Array(arguments.length-2),l=2;l<arguments.length;l++)k[l-2]=arguments[l];return b.prototype[c].apply(a,k)}},ra=function(a){if(Error.captureStackTrace)Error.captureStackTrace(this,ra);else{var b=Error().stack;b&&(this.stack=b)}a&&(this.message=String(a))},sa=function(a,b){return 0==a.lastIndexOf(b,0)},ta=function(a,b){var c=a.length-b.length;return 0<=c&&a.indexOf(b,c)==c},C=function(a){return/^[\s\xa0]*$/.test(a)},ua=function(a){return(0,window.encodeURIComponent)(String(a))},va=function(a){return(0,window.decodeURIComponent)(a.replace(/\+/g," "))},Da=function(a){if(!wa.test(a))return a;-1!=a.indexOf("&")&&(a=a.replace(xa,"&amp;"));-1!=a.indexOf("<")&&(a=a.replace(ya,"&lt;"));-1!=a.indexOf(">")&&(a=a.replace(za,"&gt;"));-1!=a.indexOf('"')&&(a=a.replace(Aa,"&quot;"));-1!=a.indexOf("'")&&(a=a.replace(Ba,"&#39;"));-1!=a.indexOf("\x00")&&(a=a.replace(Ca,"&#0;"));return a},Ha=function(a){return Ea(a,"&")?"document"in q?Fa(a):Ga(a):a},Fa=function(a){var b={"&amp;":"&","&lt;":"<","&gt;":">","&quot;":'"'},c;c=q.document.createElement("div");return a.replace(Ia,function(a,e){var f=b[a];if(f)return f;if("#"==e.charAt(0)){var k=Number("0"+e.substr(1));(0,window.isNaN)(k)||(f=String.fromCharCode(k))}f||(c.innerHTML=a+" ",f=c.firstChild.nodeValue.slice(0,-1));return b[a]=f})},Ga=function(a){return a.replace(/&([^;]+);/g,function(a,c){switch(c){case "amp":return"&";case "lt":return"<";case "gt":return">";case "quot":return'"';default:if("#"==c.charAt(0)){var d=Number("0"+c.substr(1));if(!(0,window.isNaN)(d))return String.fromCharCode(d)}return a}})},Ja=function(a,b){a
W/System.err: java.lang.Exception: failed to find pattern "(var =\{.+?\}\};)"
W/System.err:     at org.schabi.newpipe.services.youtube.YoutubeVideoExtractor.matchGroup1(YoutubeVideoExtractor.java:611)
W/System.err:     at org.schabi.newpipe.services.youtube.YoutubeVideoExtractor.loadDecryptionCode(YoutubeVideoExtractor.java:570)
W/System.err:     at org.schabi.newpipe.services.youtube.YoutubeVideoExtractor.<init>(YoutubeVideoExtractor.java:95)
W/System.err:     at org.schabi.newpipe.services.youtube.YoutubeService.getExtractorInstance(YoutubeService.java:38)
W/System.err:     at org.schabi.newpipe.VideoItemDetailFragment$VideoExtractorRunnable.run(VideoItemDetailFragment.java:111)
W/System.err:     at java.lang.Thread.run(Thread.java:841)
```

Followed by this error multiple times:

```
W/System.err: org.mozilla.javascript.EcmaError: ReferenceError: "gr" is not defined. (decryptionCode#1)
W/System.err:     at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3951)
W/System.err:     at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3929)
W/System.err:     at org.mozilla.javascript.ScriptRuntime.notFoundError(ScriptRuntime.java:4019)
W/System.err:     at org.mozilla.javascript.ScriptRuntime.getNameFunctionAndThis(ScriptRuntime.java:2314)
W/System.err:     at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1313)
W/System.err:     at script.decrypt(decryptionCode:1)
W/System.err:     at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
W/System.err:     at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
W/System.err:     at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
W/System.err:     at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282)
W/System.err:     at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
W/System.err:     at org.schabi.newpipe.services.youtube.YoutubeVideoExtractor.decryptSignature(YoutubeVideoExtractor.java:590)
W/System.err:     at org.schabi.newpipe.services.youtube.YoutubeVideoExtractor.getVideoStreams(YoutubeVideoExtractor.java:246)
W/System.err:     at org.schabi.newpipe.services.VideoExtractor.getVideoInfo(VideoExtractor.java:88)
W/System.err:     at org.schabi.newpipe.services.youtube.YoutubeVideoExtractor.getVideoInfo(YoutubeVideoExtractor.java:370)
W/System.err:     at org.schabi.newpipe.VideoItemDetailFragment$VideoExtractorRunnable.run(VideoItemDetailFragment.java:112)
W/System.err:     at java.lang.Thread.run(Thread.java:841)
```

These errors suggest that the decryption javascript function isn't being harvested correctly (at least for me anymore).

Because no-one else seems to be having this problem (I imagine I wouldn't be the only one mentioning it otherwise), I'll see if it's something weird on my device (which, for the record, is a 2012-edition Nexus 7, running CyanogenMod 11, equivalent to android 4.4.4)

**Comment by medavox** [comment]
Just uninstalled and reinstalled NewPipe, and rebooted my device.
It's still happening. I found another example:

* Search for "lol"
* Tap the video named "LOL Is An Open Door" (is the first result for me)
* Try to play it with the red button
* You should get the "Can't play this video." message

It's not happening on all videos. This is very weird.

**Comment by theScrabi** [comment]
Yea it happens to almost every video I'd like to watch now. We might have to check the extractor from the ground up. Also the javascript part already failed once so it might be that its the source of the error again.

**Comment by wb9688** [comment]
I have the same problem :-(
Op 20 dec. 2015 02:07 schreef "Christian Schabesberger" <
notifications@github.com>:

**Comment by KartikeyaShukla** [comment]
yt vids protected with signature encryprition don't work anymore. Rest play fine. Same problem with other yt apps for android like dentex yt downloader on github

**Comment by theScrabi** [comment]
Yup I noticed that. We had such an error just a few weeks ago. No big deal ( again I hope).

**Comment by theScrabi** [comment]
Should be fixed by now.

**Comment by KartikeyaShukla** [comment]
Works perfectly fine. Cheers
