### ISSUE TITLE
Crashing application at VideoDetail

### ISSUE THREAD

**Issue by SmartDroidDeveloper** [theScrabi/NewPipe#192]
Hello I'm using your latest updated code with replaced package name. When I search keyword "Matchbox" and click on any video to see detail page then application is crashing with following error. Please suggest me why this happened in my project.

[02-18 17:20:58.399 10208-10791/com.ecomapps.downloader E/AndroidRuntime: FATAL EXCEPTION: Thread-4778
                                                                         java.lang.NoClassDefFoundError: org.mozilla.javascript.Kit
                                                                             at org.mozilla.javascript.ScriptRuntime.<clinit>(ScriptRuntime.java:112)
                                                                             at org.mozilla.javascript.Context.<clinit>(Context.java:301)
                                                                             at com.ecomapps.downloader.crawler.services.youtube.YoutubeStreamExtractor.decryptSignature(YoutubeStreamExtractor.java:684)
                                                                             at com.ecomapps.downloader.crawler.services.youtube.YoutubeStreamExtractor.getAudioStreams(YoutubeStreamExtractor.java:390)
                                                                             at com.ecomapps.downloader.crawler.VideoInfo.getVideoInfo(VideoInfo.java:60)
                                                                             at com.ecomapps.downloader.VideoItemDetailFragment$VideoExtractorRunnable.run(VideoItemDetailFragment.java:135)
                                                                             at java.lang.Thread.run(Thread.java:841)](url)

**Comment by theScrabi** [comment]
What means the latest version 0.7.3, 0.7.4? 
Also:
 * from which country are you trying to connect. I's it still happening when you try it via tor?
 * can you please give a link to a certain video. You can search for them on the regular youtube website.

**Comment by SmartDroidDeveloper** [comment]
Hi Christian Schabesberger,

   Latest version means 0.7.4, I am facing the problem. I'm trying to
connect from India and It is not happening via TOR. It's simply happen
while clicking
on some videos.
The link is below which is not visible in some version of android.
https://r6---sn-cvh7zn7s.googlevideo.com/videoplayback?requiressl=yes&nh=IgpwcjAxLmJvbTA3KgkxMjcuMC4wLjE&expire=1456311341&ratebypass=yes&ipbits=0&sparams=dur%2Cgcr%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cnh%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cupn%2Cexpire&mime=video%2Fwebm&upn=0Ma2fy565P0&gcr=in&initcwndbps=345000&itag=43&sver=3&pl=22&fexp=9406821%2C9408505%2C9413137%2C9416126%2C9420452%2C9421527%2C9422544%2C9422596%2C9423661%2C9423662%2C9423847%2C9427676%2C9427769%2C9427824%2C9428010%2C9428650%2C9428856%2C9428947%2C9428969%2C9429118%2C9429175%2C9429220&ip=115.118.14.122&key=yt6&lmt=1280194276500658&ms=au&source=youtube&mv=m&id=o-ACwnOZmqf9jQvMk-K7c-AooMYND05oUecnCA2Ra3bpGo&dur=0.000&mt=1456289605&mm=31&mn=sn-cvh7zn7s&signature=DD7F706F6BA2DDDEDB4F31A73E3B6465584A6FC0.886770A8C4C615C9386B8A2D49F7C87E8AB807AA

And If you search "Matchbox" in serach bar  and click on second video,
crashing occurs on video detail. Please let me know why this is happening.

Hoping for favorable reply. Thank you.

*Thanks,*
*Yasmik Patel*

**Comment by theScrabi** [comment]
This is a stream link right? They expire after some time. Also 0.7.4 is not the latest version anymore.  I need the link to the website of the video. Also please try 0.7.6 because in 0.7.5 there where some havy updates.

**Comment by SmartDroidDeveloper** [comment]
Thanks Scrabi. Using your latest version 0.7.6, I resolved problem and works fine.

**Comment by theScrabi** [comment]
ok good :)
