### ISSUE TITLE
HELP! NewPipe is not working

### ISSUE THREAD

**Issue by xlinulx** [theScrabi/NewPipe#298]
org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor$DecryptException: Could not parse decrypt function 
 at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:775)
 at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.<init>(YoutubeStreamExtractor.java:211)
 at org.schabi.newpipe.extractor.services.youtube.YoutubeService.getExtractorInstance(YoutubeService.java:50)
W/System.err:     at android.os.AsyncTask$2.call(AsyncTask.java:295)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
W/System.err:     at java.lang.Thread.run(Thread.java:818)
W/System.err: Caused by: org.schabi.newpipe.extractor.Parser$RegexException: failed to find pattern ";([A-Za-z0-9_\$]{2})\...\( inside of var or=function(){b(!1)};"
System.err:     at org.schabi.newpipe.extractor.Parser.matchGroup1(Parser.java:51)
  at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:762)

**Comment by xlinulx** [comment]
Caused by: org.schabi.newpipe.extractor.Parser$RegexException: failed to find pattern ";([A-Za-z0-9_\$]{2})...( inside of var or=function(){b(!1)};"
System.err: at org.schabi.newpipe.extractor.Parser.matchGroup1(Parser.java:51)
at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.loadDecryptionCode(YoutubeStreamExtractor.java:762)

**Comment by satiricon** [comment]
@xlinulx I'm on it.

**Comment by theScrabi** [comment]
@satiricon I was yust about to answer. Nice thanks.

**Comment by satiricon** [comment]
@theScrabi If you know how to fix it fast I can step aside. It's obviously a regex problem but I'm still not familiar with the parsing part of the app.

**Comment by satiricon** [comment]
The problem is in this line.

`helperObjectName = Parser.matchGroup1(";([A-Za-z0-9_\\$]{2})\\...\\(", decryptionFunc);`

The value of decryptionFunc

`var or=function(){b(!1)};`

**Comment by satiricon** [comment]
Got it.

**Comment by xlinulx** [comment]
Did you solve it?

**Comment by satiricon** [comment]
@xlinulx Kind of. 

I got it working when I view a video from the search list but the app crashes when I want to watch a video from the "similar videos" list.

**Comment by xlinulx** [comment]
Can you please post, how did you solve it? (to teach myself)

**Comment by satiricon** [comment]
I checked the regexps and watched that the results made sense in the context it was running. 

The real problem is in this code.

`String functionPattern = "("
                    + decryptionFuncName.replace("$", "\\$")
                    + "=function\\([a-zA-Z0-9_]*\\)\\{.+?\\})";
decryptionFunc = "var " + Parser.matchGroup1(functionPattern, playerCode) + ";";`

When it parses the youtube code it brings the wrong result. That's why to fix it I just added another constraint to make sure the right result was returned.

Changed: 

`=function\([a-zA-Z0-9_]*\)\{.+?\})`

to:

`=function\([a-zA-Z0-9_]+\)\{.+?\})`

**Comment by xlinulx** [comment]
Wonderfully working, thank you :))))

**Comment by satiricon** [comment]
It's working fine now.
