### ISSUE TITLE
Audio not downloadable or streamable

### ISSUE THREAD

**Issue by unicorn622** [theScrabi/NewPipe#304]
Hey, 

it seems like for some videos it is not possible to fetch the audio link. I can only download and watch the video. Streaming and downloading of the audio is not possible.

Here is the crash log which NewPipe provides:

{
   "user_action": "requested stream",
   "request": "https:\/\/www.youtube.com\/watch?v=xxx", //should i provide a youtube link?
   "content_language": "en",
   "service": "Youtube",
   "version": "0.7.8",
   "os": "Linux Android 6.0.1 - 23",
   "time": "2016-06-02 13:05",
   "ip_range": "xx.xx.xx.xx", //removed by me
   "exceptions": [
      "org.schabi.newpipe.extractor.ExtractionException: Couldn't get audio streams 
at org.schabi.newpipe.extractor.StreamInfo.extractStreams(StreamInfo.java:125) 
at org.schabi.newpipe.extractor.StreamInfo.getVideoInfo(StreamInfo.java:76) 
at org.schabi.newpipe.VideoItemDetailFragment$VideoExtractorRunnable.run(VideoItemDetailFragment.java:141) at java.lang.Thread.run(Thread.java:818)
Caused by: org.schabi.newpipe.extractor.ParsingException: Could not get audiostreams 
at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.getAudioStreams(YoutubeStreamExtractor.java:471) 
at org.schabi.newpipe.extractor.StreamInfo.extractStreams(StreamInfo.java:123)
... 3 more
Caused by: org.json.JSONException: No value for adaptive_fmts
at org.json.JSONObject.get(JSONObject.java:389)
at org.json.JSONObject.getString(JSONObject.java:550)
at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.getAudioStreams(YoutubeStreamExtractor.java:443)
... 4 more\n"
   ],
   "user_comment": ""
}

**Comment by theScrabi** [comment]
Please use the build in buckreport tool.
