### ISSUE TITLE
Exception when using youtube's android standard url scheme.

### ISSUE THREAD

**Issue by satiricon** [theScrabi/NewPipe#310]
```
org.schabi.newpipe.extractor.Parser$RegexException: failed to find pattern \"[?&amp;]v=([\\-a-zA-Z0-9_]{11}) inside of vnd.youtube:JYB5vT9HIaQ?vndel=watch&amp;vndclient=mv-google&amp;vndapp=youtube_mobile
at org.schabi.newpipe.extractor.Parser.matchGroup1(Parser.java:53)
at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamUrlIdHandler.getVideoId(YoutubeStreamUrlIdHandler.java:52)
at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamUrlIdHandler.cleanUrl(YoutubeStreamUrlIdHandler.java:75)
at org.schabi.newpipe.extractor.services.youtube.YoutubeStreamExtractor.(YoutubeStreamExtractor.java:190)
at org.schabi.newpipe.extractor.services.youtube.YoutubeService.getExtractorInstance(YoutubeService.java:50)
at org.schabi.newpipe.VideoItemDetailFragment$VideoExtractorRunnable.run(VideoItemDetailFragment.java:140)
at java.lang.Thread.run(Thread.java:841
```

**Comment by satiricon** [comment]
Fixed.
