### ISSUE TITLE
MPDroid crashes when pressing the Headphones-Icon

### ISSUE THREAD

**Issue by MartiniMoe** [theScrabi/NewPipe#62]
Hi there,
I think the headphones icon is for streaming audio only, right?
When I click it, I only get the notification, that MPDroid crashed and then Im back at the search results page of NewPipe.
Why does it even want to use MPDroid?

Thanks and keep developing this great App :)

// When I install VLC and chose that it works

**Comment by theScrabi** [comment]
Yes i noticed that, i thought it would be a problem from MPDroid.

**Comment by theScrabi** [comment]
So i found the error is truly happening inside MPdroid. Here is the stacktrace:
```
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.namelessdev.mpdroid/com.namelessdev.mpdroid.URIHandlerActivity}: java.lang.ClassCastException: com.namelessdev.mpdroid.URIHandlerActivity cannot be cast to android.support.v7.app.ActionBarActivity
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2358)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:154)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5292)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:  Caused by: java.lang.ClassCastException: com.namelessdev.mpdroid.URIHandlerActivity cannot be cast to android.support.v7.app.ActionBarActivity
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at com.namelessdev.mpdroid.fragments.BrowseFragment.onActivityCreated(BrowseFragment.java:255)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at com.namelessdev.mpdroid.fragments.StreamsFragment.onActivityCreated(StreamsFragment.java:274)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1794)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:967)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1126)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1108)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.support.v4.app.FragmentManagerImpl.dispatchActivityCreated(FragmentManager.java:1917)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.support.v4.app.FragmentActivity.onStart(FragmentActivity.java:544)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1236)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.app.Activity.performStart(Activity.java:6006)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2321)
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2420) 
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:154) 
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1321) 
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135) 
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5292) 
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method) 
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372) 
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:904) 
10-29 18:29:31.310 30701-30701/com.namelessdev.mpdroid E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:699) 
```

Please report it here:
https://github.com/abarisain/dmix/issues
